const withOpacity = (variableName) => {
  return ({ opacityValue }) => {
    if (opacityValue !== undefined) {
      return `rgba(var(${variableName}), ${opacityValue})`;
    }
    return `rgb(var(${variableName}))`;
  };
};
/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: [
    "./App.tsx",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./node_modules/@rnr/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    fontFamily: {
      "primary-regular": [
        "Teshrin-Regular",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      "primary-medium": [
        "Teshrin-Medium",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      "primary-bold": [
        "Teshrin-Bold",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
    },
    extend: {
      colors: {
        primary: {
          ruby: withOpacity("--color-primary-ruby"),
          creem: withOpacity("--color-primary-creem"),
        },
        secondary: {
          ruby: withOpacity("--color-secondary-ruby"),
          purple: withOpacity("--color-secondary-purple"),
          yellow: withOpacity("--color-secondary-yellow"),
          green: withOpacity("--color-secondary-green"),
          blue: withOpacity("--color-secondary-blue"),
          orange: withOpacity("--color-secondary-orange"),
          gray: withOpacity("--color-secondary-gray"),
          white: withOpacity("--color-secondary-white"),
          smoke: withOpacity("--color-secondary-smoke"),
        },
        shades: {
          ruby: {
            "01": withOpacity("--color-shades-ruby-01"),
            "02": withOpacity("--color-shades-ruby-02"),
            "03": withOpacity("--color-shades-ruby-03"),
            "04": withOpacity("--color-shades-ruby-04"),
            "05": withOpacity("--color-shades-ruby-05"),
          },
          creem: {
            "01": withOpacity("--color-shades-creem-01"),
            "02": withOpacity("--color-shades-creem-02"),
            "03": withOpacity("--color-shades-creem-03"),
            "04": withOpacity("--color-shades-creem-04"),
            "05": withOpacity("--color-shades-creem-05"),
          },
          purple: {
            "01": withOpacity("--color-shades-purple-01"),
            "02": withOpacity("--color-shades-purple-02"),
            "03": withOpacity("--color-shades-purple-03"),
            "04": withOpacity("--color-shades-purple-04"),
            "05": withOpacity("--color-shades-purple-05"),
            "06": withOpacity("--color-shades-purple-06"),
          },
          yellow: {
            "01": withOpacity("--color-shades-yellow-01"),
            "02": withOpacity("--color-shades-yellow-02"),
            "03": withOpacity("--color-shades-yellow-03"),
            "04": withOpacity("--color-shades-yellow-04"),
            "05": withOpacity("--color-shades-yellow-05"),
            "06": withOpacity("--color-shades-yellow-06"),
          },
          green: {
            "01": withOpacity("--color-shades-green-01"),
            "02": withOpacity("--color-shades-green-02"),
            "03": withOpacity("--color-shades-green-03"),
            "04": withOpacity("--color-shades-green-04"),
            "05": withOpacity("--color-shades-green-05"),
            "06": withOpacity("--color-shades-green-06"),
          },
          blue: {
            "01": withOpacity("--color-shades-blue-01"),
            "02": withOpacity("--color-shades-blue-02"),
            "03": withOpacity("--color-shades-blue-03"),
            "04": withOpacity("--color-shades-blue-04"),
            "05": withOpacity("--color-shades-blue-05"),
            "06": withOpacity("--color-shades-blue-06"),
          },
          orange: {
            "01": withOpacity("--color-shades-orange-01"),
            "02": withOpacity("--color-shades-orange-02"),
            "03": withOpacity("--color-shades-orange-03"),
            "04": withOpacity("--color-shades-orange-04"),
            "05": withOpacity("--color-shades-orange-05"),
            "06": withOpacity("--color-shades-orange-06"),
          },
          gray: {
            "01": withOpacity("--color-shades-gray-01"),
            "02": withOpacity("--color-shades-gray-02"),
            "03": withOpacity("--color-shades-gray-03"),
            "04": withOpacity("--color-shades-gray-04"),
            "05": withOpacity("--color-shades-gray-05"),
            "06": withOpacity("--color-shades-gray-06"),
          },
          border: {
            "01": withOpacity("--color-shades-border-01"),
            "02": withOpacity("--color-shades-border-02"),
            "03": withOpacity("--color-shades-border-03"),
          },
        },
      },
      fontSize: {
        xxs: ["10px", { lineHeight: "14px" }],
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "22px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "26px" }],
        xl: ["20px", { lineHeight: "32px" }],
        xxl: ["24px", { lineHeight: "40px" }],
      },
      margin: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "38px",
        10: "40px",
      },
      padding: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "38px",
        10: "40px",
      },
      "custom-transition-all": "transition-all duration-500 ease-in",
      "custom-transition-colors": "transition-colors duration-500 ease-in",
      "custom-transition-opacity": "transition-opacity duration-500 ease-in",
    },
  },
  plugins: [],
};
