const constants = {
  animateAll: "transition-all duration-300 ease-in",
  animateColors: "transition-colors duration-300 ease-in",
  animateOpacity: "transition-opacity duration-300 ease-in",
  actionOpacity: "hover:web:opacity-70 active:opacity-70",
  fontPrimaryRegular: "font-primary-regular",
  fontPrimaryMedium: "font-primary-medium",
  fontPrimaryBold: "font-primary-bold",
  tabs: [
    {
      name: "index",
      activeIcon: "tabHomeSelected",
      inActiveIcon: "tabHome",
      title: "tabs.home",
      activeIconSize: { width: 24, height: 24 },
      inActiveIconSize: { width: 24, height: 24 },
      showHeader: false,
      telcoUserRequired: true,
      showHelp: false,
    },
    {
      name: "usage",
      activeIcon: "tabUsageSelected",
      inActiveIcon: "tabUsage",
      title: "tabs.usage",
      activeIconSize: { width: 20, height: 20 },
      inActiveIconSize: { width: 24, height: 24 },
      showHeader: true,
      telcoUserRequired: true,
      showHelp: false,
    },
    {
      name: "store",
      activeIcon: "tabStoreSelected",
      inActiveIcon: "tabStore",
      title: "tabs.store",
      activeIconSize: { width: 24, height: 24 },
      inActiveIconSize: { width: 24, height: 24 },
      showHeader: false,
      telcoUserRequired: false,
      showHelp: false,
    },
    {
      name: "settings",
      activeIcon: "tabSettingSelected",
      inActiveIcon: "tabSetting",
      title: "tabs.settings",
      activeIconSize: { width: 24, height: 24 },
      inActiveIconSize: { width: 24, height: 24 },
      showHeader: true,
      telcoUserRequired: false,
      showHelp: true,
    },
  ],
  creditCardType: {
    visa: "visa",
    mastercard: "mastercard",
    amex: "amex",
    mada: "mada",
  },
  userTypes: {
    telco: "TELCO",
    guest: "GUEST",
    nonTelco: "NON_TELCO",
  },
  bottomTabHeight: 85,
  collapsableHeaderHeight: 395,
  tabScreenBottomPadding: 120,
  webWidth: 750,
  paymentFor: {
    renewPackage: "renew-package",
    orderSIM: "order-sim",
    activatSIM: "activate-sim",
    orderDevice: "order-device",
    addApps: "add-apps",
  },
  paymentMethod: {
    apple: "apple",
    creditDebitCard: "creditDebitCard",
    mokafaa: "mokafaa",
    bnpl: "bnpl",
    googlePay: "googlePay",
    wallet: "wallet",
  },
  successFlowType: {
    renewPackage: "renew-package",
    unlimitedAppsSelection: "unlimited_apps_selection",
    callWaitingService: "call_waiting_service",
    blockPromotionalSMSYaqoot: "block_promotional_sms_yaqoot",
    blockPromotionalSMSAll: "block_promotional_sms_all",
    blockSpecificSender: "block_specific_sender",
    cancelCallSMSServices: "cancel_call_sms_services",
    activateVoicemailAllCases: "activate_voicemail_all_cases",
    activateVoicemailChosenCategory: "activate_voicemail_choosen_category",
    activateMissedCallSMSAllCases: "activate_missedcallsms_all_cases",
    activateMissedCallSMSChosenCategory:
      "activate_missedcallsms_choosen_category",
    orderSIM: "order_sim",
    eSIMActivated: "esim_activated",
    simActivated: "sim_card_activated",
    orderPaymet: "order-payment",
    welcomeToYaqoot: "welcome_to_yaqoot",
    orderDeviceSuccess: "order-device-success",
    autoRenewCancel: "auto-renew-cancel",
    autoRenewSetup: "auto-renew-setup",
    autoRenewResume: "auto-renew-resume",
    addAppSuccess: "add-app-success",
    cancelOrderSuccess: "cancel-order-success",
    addressUpdated: "address-updated",
    multilineRenewal: "multiline-renewal",
  } as const,
  errorType: {
    somethingWentWrong: "something-went-wrong",
    nafathCodeExpire: "nafath-code-expire",
    nafathVerificationFail: "nafath-verification-fail",
    orderLimitExceed: "order-limit-exceed",
    activationNationalIDMismatch: "activation-national-id-mismatch",
  },
  journeyType: {
    orderSim: "order-sim",
  },
  NEW_ORDER: "NEW_ORDER",
  SIM_ORDER: "SIM_ORDER",
  userRegistration: "USER_REGISTRATION",
  nafathJourneyServiceMap: {
    newNumber: "IssueNewMobileIndividual",
    transferMobileOwnershipBetweenNetworks:
      "TransferMobileOwnershipBetweenNetworks",
    issueNewSimIndividual: "IssueNewSimIndividual",
  },
  saudiCountryCode: 113, // for semati this natioanlity code use
  saudiDialCode: "+966",
  whatsAppUrl: "chat.whatsapp.com",
  helpLineNumber: "05xxxxxxx",
  MAX_CARD_ADD_LIMIT: 3,
  textRTL: "text-left",
  routesRequiringBackConfirmation: [
    "delivery-information",
    "review-order",
  ],
  routesNavigateToHomeOnBack: ["success", "order-confirmed", "reviewpayment"],
  REFRESH_FLAG: "JOURNEY_REFRESH_ALERT_SHOWN",
  CHANGE_LANGUAGE_FLAG: "CHANGE_LANGUAGE_FLAG",
};

export default constants;
